In [1]:
import numpy as np

In [2]:
x = np.random.rand(3,4)
b = np.random.rand(4)
x+b

array([[1.69597251, 0.34377289, 1.01856868, 0.81707973],
       [0.95623088, 0.43710964, 1.23145792, 1.01508968],
       [0.96254266, 0.89836146, 1.65040835, 0.48227851]])

In [3]:
x = np.random.rand(3,4)
b = np.random.rand(3,4)
x*b

array([[0.00069034, 0.03786157, 0.1090738 , 0.36450342],
       [0.18922107, 0.00084515, 0.17146384, 0.01994041],
       [0.57042981, 0.42109879, 0.04345876, 0.45473641]])

In [4]:
N, T, D = 2, 3, 4

x = np.linspace(-0.1, 0.3, num=N*T*D).reshape(N, T, D)

In [10]:
for i in range(T):
    print(x[:,i,:].shape)

(2, 4)
(2, 4)
(2, 4)


In [13]:
N= 3
T = 4
dx_flat = np.zeros([3*4, 10])
y_flat = np.random.randint(0,10,size=(12,))
dx_flat[np.arange(N * T), y_flat] -= 1

In [14]:
y_flat

array([4, 1, 4, 4, 0, 3, 5, 8, 1, 7, 2, 3])

In [17]:
dx_flat[np.arange(N * T), y_flat]

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [18]:
_null = 0
captions = _null * np.ones((4, 40), dtype=np.int32)

In [19]:
captions

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)